# Generated by Django 3.2 on 2021-04-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('issued', models.BooleanField(default=False)),
                ('requests', models.IntegerField(default=0)),
            ],
        ),
    ]
